/// <reference types="vite/client" />

// Ambient type for the module generated by kratosAdminVite()/kratosViewsVite().
declare module 'virtual:kratos-client' {
	import type { KratosPluginClient } from '@maxal_studio/kratosjs-react/plugin';
	export const pluginClients: KratosPluginClient[];
}
